"""add_stripe_and_subscription_columns

Revision ID: 15adcab47b70
Revises: 3f1f11164807
Create Date: 2025-10-07 14:54:48.216180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15adcab47b70'
down_revision: Union[str, None] = '3f1f11164807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer_id')
    op.alter_column('booking', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
