"""add_missing_user_subscription_fields

Revision ID: 3f1f11164807
Revises: a937903701f7
Create Date: 2025-09-01 20:08:18.299490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1f11164807'
down_revision: Union[str, None] = 'a937903701f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('assistant', sa.Column('enabled_features', sa.Text(), nullable=True))
    op.add_column('assistant', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('assistant', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('plan', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('subscription_status', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('subscription_id', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('subscription_updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('max_agents', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('allowed_addons', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'allowed_addons')
    op.drop_column('user', 'max_agents')
    op.drop_column('user', 'subscription_updated_at')
    op.drop_column('user', 'subscription_id')
    op.drop_column('user', 'subscription_status')
    op.drop_column('user', 'plan')
    op.drop_column('assistant', 'updated_at')
    op.drop_column('assistant', 'created_at')
    op.drop_column('assistant', 'enabled_features')
    op.drop_column('assistant', 'status')
    # ### end Alembic commands ###
